# Generated by Django 4.0.3 on 2022-08-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_address', models.CharField(max_length=1000)),
                ('view_key', models.CharField(max_length=1000)),
            ],
        ),
    ]
