# Generated by Django 4.0.3 on 2022-08-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_userwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='phone_number',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
