# Generated by Django 4.0.3 on 2022-09-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_userwallet_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='client_type',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='tsp_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
