# Generated by Django 4.0.3 on 2022-10-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_userwallet_client_type_userwallet_tsp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='spend_key',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
